meta:
  environment: postgres-warden

  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: postgres
    networks:
      - name: postgres1
        static_ips: (( static_ips 0 1 2 3 4 5 6 7 8 9 ))

compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: small_z1
    cloud_properties:
      name: random

networks:
- name: postgres1
  type: manual
  subnets:
  - range: 10.244.232.0/24
    name: postgres1
    gateway: 10.244.232.1
    static:
      - 10.244.232.2 - 10.244.232.60
