meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: postgres
    templates:
    - { release: postgres, name: postgres }
    - { release: postgres, name: pgpool }
    instances: 3
    persistent_disk: 0
    resource_pool: small_z1
    networks: (( param "please set postgres networks" ))

    properties:
      postgres:
        config:
          port: 6432
        replication:
          enabled: true
          master: (( grab jobs.postgres.networks.postgres1.static_ips[0] ))
          pool:   (( grab jobs.postgres.networks.postgres1.static_ips ))
        hba:
          - host all all 0.0.0.0/0 md5
          - host all all ::/0 md5
      pgpool:
        debug: true
        users:
          - username: porcupine
            password: quill
          - username: hedgehog
            password: frank
        backend:
          hosts: (( grab jobs.postgres.networks.postgres1.static_ips ))
          port: 6432
        config:
          port: 5432
          enable_pool_hba: on
        hba: (( grab jobs.postgres.properties.postgres.hba ))
      pcp:
        system_password: secret


networks: (( param "please set networks" ))

properties: {}
